# Generated by Django 4.2.23 on 2025-08-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiptier",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="currency",
            field=models.CharField(default="NPR", max_length=3),
        ),
    ]
