# Generated by Django 4.2.23 on 2025-08-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0002_membershiptier_stripe_price_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenthistory",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card", "Credit/Debit Card"),
                    ("khalti", "Khalti"),
                    ("esewa", "eSewa"),
                    ("cash", "Cash at Counter"),
                    ("stripe", "Stripe"),
                ],
                max_length=50,
            ),
        ),
    ]
