# Generated by Django 4.2.23 on 2025-08-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_booking_booking_status_booking_cancellation_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit_card", "Credit/Debit Card"),
                    ("khalti", "Khalti"),
                    ("esewa", "eSewa"),
                    ("cash", "Cash at Counter"),
                ],
                max_length=20,
            ),
        ),
    ]
