# Generated by Django 4.2.23 on 2025-08-02 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("action", "Action"),
                            ("comedy", "Comedy"),
                            ("drama", "Drama"),
                            ("horror", "Horror"),
                            ("romance", "Romance"),
                            ("sci-fi", "Sci-Fi"),
                            ("thriller", "Thriller"),
                            ("documentary", "Documentary"),
                            ("animation", "Animation"),
                            ("adventure", "Adventure"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("english", "English"),
                            ("hindi", "Hindi"),
                            ("spanish", "Spanish"),
                            ("french", "French"),
                            ("german", "German"),
                            ("chinese", "Chinese"),
                            ("japanese", "Japanese"),
                            ("korean", "Korean"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration", models.IntegerField(help_text="Duration in minutes")),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                (
                    "poster",
                    models.ImageField(
                        blank=True, null=True, upload_to="movie_posters/"
                    ),
                ),
                ("trailer_url", models.URLField(blank=True, null=True)),
                ("description", models.TextField()),
                ("release_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-release_date"],
            },
        ),
    ]
