# Generated by Django 4.2.23 on 2025-08-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="language",
            field=models.CharField(
                choices=[
                    ("english", "English"),
                    ("hindi", "Hindi"),
                    ("nepali", "Nepali"),
                    ("spanish", "Spanish"),
                    ("french", "French"),
                    ("german", "German"),
                    ("chinese", "Chinese"),
                    ("japanese", "Japanese"),
                    ("korean", "Korean"),
                ],
                max_length=20,
            ),
        ),
    ]
