# Generated by Django 4.2.23 on 2025-08-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_alter_movie_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="poster_url",
            field=models.URLField(
                blank=True, help_text="External URL for movie poster", null=True
            ),
        ),
    ]
