# Generated by Django 4.2.23 on 2025-08-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_movie_poster_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="cast",
            field=models.TextField(
                blank=True, help_text="Comma-separated list of main cast", null=True
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
